addMethods
Anastasiyyya/HOTWIRE_COM pull request #1
Opened 2021-07-27 07:00 UTC by Anastasiyyya

2021-07-28 08:35 UTC, vladimir-moshkov requested changes

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/Airline.java
> +    private String[] logo;
Лого - это картинка? Почему хранится в массиве стрингов?

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/Currency.java
> +    Currency currency;
Зачем нужно это поле? 
В модели его нет

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/FlightFilter.java
> +    private Passenger[] passengers;
не проще ли использовать коллекцию, а не массив? 
тогда и метод addPassengerToList будет выглядеть проще

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/Passenger.java
> +            return 0;
А для чего нам нужна эта логика с null значениями? Может быть ситуация, когда какая-то из дат не задается, и тогда считается, что пассажир несовершеннолетний?

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
Что делает этот метод?

2021-07-28 08:35 UTC, vladimir-moshkov commented on src/main/java/classes/TicketPrice.java
> +    public String getSum(){
Переименовать метод. 
getSum - это геттер поля

2021-08-05 07:15 UTC, Anastasiyyya commented on src/main/java/classes/Airline.java
> +package classes;
Исправила на entities

2021-08-05 07:18 UTC, Anastasiyyya commented on src/main/java/classes/Airline.java
> +    private String[] logo;
Изменила на String logoUrl

2021-08-05 07:19 UTC, Anastasiyyya commented on src/main/java/classes/Currency.java
> +    Currency currency;
удалено

2021-08-05 07:23 UTC, Anastasiyyya commented on src/main/java/classes/Passenger.java
> +            return 0;
исправлено

2021-08-05 07:23 UTC, Anastasiyyya commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
Получает данные с именем и фамилией пассажира

2021-08-05 07:24 UTC, Anastasiyyya commented on src/main/java/classes/TicketPrice.java
> +    public String getSum(){
переименован

2021-08-05 07:24 UTC, Anastasiyyya commented on src/main/java/classes/FlightFilter.java
> +    private Passenger[] passengers;
да, можно и коллекцией)

2021-08-05 07:36 UTC, Anastasiyyya commented on src/main/java/classes/FlightFilter.java
> +    private Passenger[] passengers;
исправлено

2021-08-05 14:50 UTC, vladimir-moshkov commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
- [ ] тогда его нужно переименовать на что-то другое.

2021-08-05 15:13 UTC, vladimir-moshkov requested changes

2021-08-05 15:13 UTC, vladimir-moshkov commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
Переименовать метод

2021-08-06 08:01 UTC, Anastasiyyya commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
переименовала метод на makeUpPassengerFullName

2021-08-06 08:08 UTC, Anastasiyyya commented on src/main/java/entities/Flight.java
> +        return String.format("%s %s", Arrays.toString(airline.getLogo()), airline.getAirlineName());
Название метода изменено на makeUpAirlineInformation

2021-08-06 09:25 UTC, Anastasiyyya commented on src/main/java/entities/FlightFilter.java
> +    private Passenger[] passengers;
изменила массив Flight  в классе FlightsList на List<Flight>, а также List<Passenger> в классе FlightFilter

2021-08-06 09:25 UTC, Anastasiyyya commented on src/main/java/entities/FlightFilter.java
> +        ArrayList<Passenger> passengersList = new ArrayList<>();
изменила метод в соответствии с замечанием

2021-08-06 09:26 UTC, Anastasiyyya commented on src/main/java/classes/Passenger.java
> +    public String createPassenger(String passengerName, String passengerSurname) {
Название метода изменено на makeUpPassengerFullName

2021-08-06 13:57 UTC, vladimir-moshkov commented
У тебя в проекте сейчас модуль OOP и корневая старая папка src. Удали её. 
И перед отправлением на ревью пробуй выполнять билд проекта. Тогда будешь видеть, есть ли ошибки какие-то.

2021-08-06 14:48 UTC, merged