Add PageObject Model
Anastasiyyya/HOTWIRE_COM pull request #2
Opened 2021-08-06 14:22 UTC by Anastasiyyya

2021-08-16 14:33 UTC, vladimir-moshkov requested changes

2021-08-16 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/constants/IConstantsURL.java
> +    String FLIGHTS_PAGE_URL = "https://www.hotwire.com/";
Почему 2 одинаковых урла на 2 разные страницы?

2021-08-16 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/pages/BasePageForm.java
> +    private SelenideElement flyFromField;
Зачем эти переменные, которые нигде не используются и нигде не определены?
И так много в каких классах. Надо убрать ненужные поля

2021-08-16 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/pages/BasePage.java
> +                "5949BB4D1CE164DBFF9FA3CE76ECB53C~000000000000000000000000000000~YAAQX/" +
У тебя выполняется открытие страницы BASE_PAGE_URL и добавляются куки в нескольких классах? Для чего? 
По идее BASE_PAGE_URL у тебя должна иметь только одна страница, а значит и один класс

2021-08-16 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/elements/DropdownMenu.java
> +        $$(CURRENCY_CONTAINER).get(4).click();
get(4) - нужно убрать. 
Метод должен выглядеть так:
changeCurrency(String currencyCode)

2021-08-19 09:36 UTC, Anastasiyyya commented on PageObject/src/main/java/elements/DropdownMenu.java
> +        $$(CURRENCY_CONTAINER).get(4).click();
исправлено

2021-08-19 09:37 UTC, Anastasiyyya commented on PageObject/src/main/java/constants/IConstantsURL.java
> +    String FLIGHTS_PAGE_URL = "https://www.hotwire.com/";
исправлено

2021-08-19 14:37 UTC, vladimir-moshkov commented
Смотри внимательно мои замечания, пожалуйста. 
Мы договаривались, что описание одной страницы - один класс. 
А у тебя BASE_PAGE_URL открывается в двух классах. 
Если у тебя есть какая-то форма на странице, она должна быть представлена полем в классе этой страницы. А внутри класса формы ничего дублировать не надо.
пересмотри внимательно свою структуру и сделай всё правильно.

2021-08-24 07:21 UTC, merged