Tests
Anastasiyyya/HOTWIRE_COM pull request #4
Opened 2021-09-22 05:56 UTC by Anastasiyyya

2021-09-22 14:33 UTC, vladimir-moshkov requested changes

2021-09-22 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/pages/FlightsSearchPage.java
> +        Selenide.Wait().withTimeout(Duration.ofSeconds(10));
Плохое решение прям так в лоб писать ожидания. 
Во первых можно настроить implicit waitings.
Во-вторых, если делаются явные ожидания, то лучше их вешать непосредственно на сам элемент.
В твоем случае, если после 10 секунд не отобразится элемент, где у тебя тест упадет? Как потом по всему коду ходить искать, кто виновником оказался?

2021-09-22 14:33 UTC, vladimir-moshkov commented on PageObject/src/main/java/pages/FlightsSearchPage.java
> +        Selenide.Wait().withTimeout(Duration.ofSeconds(10));
https://selenide.org/documentation.html
Здесь можно почитьать про implicit и explicit waitings

2021-09-22 14:33 UTC, vladimir-moshkov commented on Steps/src/main/java/steps/FindFlightsSteps.java
> +        int adultPassengerCount = basePage.getBasePageForm().getPassengersInput().checkExistPassengersCount(flightSearch.getPassenger().getAdultPassenger());
Почему у тебя метод check возвращает int?

2021-09-22 14:33 UTC, vladimir-moshkov commented on Steps/src/main/java/steps/FindFlightsSteps.java
> +    public boolean assertTripType() {
непонятные названия. Переназови все свои ассерты.
При этом если метод называется assert, то внутри он должен делать проверки и выкидывать ассерты
А если это boolean, то в названии он должен содержать is или has

2021-09-22 14:33 UTC, vladimir-moshkov commented on Tests/src/test/java/tests/FlightDataTests.java
> +        findFlightSteps.findSearchingResultsList(Objects.location);
У тебя все шаги в этом одном шаге спрятаны? 
Странное архитектурное решение. При этом ты не используешь возвращаемый результат метода.
Как минимум, у тебя должен быть шаг по заполнению данных с получением результата. И шаг по проверке полученных данных.

2021-09-22 14:33 UTC, vladimir-moshkov commented on Tests/src/test/java/tests/FlightDataTests.java
> +        findFlightSteps.findOneWayTripFlight(Objects.flightSearch);
Тут тоже плохо читаемый тест.
У тебя в тест кейсе проверки такие:
1) Check that every flight in flight list has direction such as:
MSQ - VKO
MSQ - DME
MSQ - SVO
2) Total amount of passengers on the new page is equal to the sum of adult passengers and children entered earlier
3) For every flight of flights list type of trip is 'roundtrip'

Т.е. 3 штуки. А здесь я вижу только 2. Выноси все три проверки, которые ты делаешь, сюда

2021-09-22 14:33 UTC, vladimir-moshkov commented on Tests/src/test/java/tests/FlightDataTests.java
> +    public void checkInputResults() {
Я прогнал первый тест. У тебя makeUpSearchingResultsList() возвращает 0, а значит и в цикле for ничего не прогоняется в методе assertionForSearchingResults(String result)

2021-09-22 14:33 UTC, vladimir-moshkov commented on Tests/src/test/java/tests/FlightDataTests.java
> +    @Test(description = "Checks that the input field works correctly")
Этот тест у меня упал

2021-09-23 06:13 UTC, Anastasiyyya commented on Steps/src/main/java/steps/FindFlightsSteps.java
> +        int adultPassengerCount = basePage.getBasePageForm().getPassengersInput().checkExistPassengersCount(flightSearch.getPassenger().getAdultPassenger());
Изменила название метода

2021-09-23 06:19 UTC, Anastasiyyya commented on Steps/src/main/java/steps/FindFlightsSteps.java
> +    public boolean assertTripType() {
Изменила названия всех asserts

2021-09-23 06:25 UTC, Anastasiyyya commented on Tests/src/test/java/tests/FlightDataTests.java
> +        findFlightSteps.findSearchingResultsList(Objects.location);
Сделала 2 шага: по получению данных и по проверке данных

2021-09-23 07:32 UTC, Anastasiyyya commented on PageObject/src/main/java/pages/FlightsSearchPage.java
> +        Selenide.Wait().withTimeout(Duration.ofSeconds(10));
удалила здесь ожидание и добавила его в checkbox

2021-09-23 11:09 UTC, Anastasiyyya commented on Tests/src/test/java/tests/FlightDataTests.java
> +        findFlightSteps.findOneWayTripFlight(Objects.flightSearch);
Исправила. Теперь  3 шага отражены самом тесте

2021-09-23 11:09 UTC, Anastasiyyya commented on Tests/src/test/java/tests/FlightDataTests.java
> +    public void checkInputResults() {
исправила, всё работает

2021-09-23 11:10 UTC, Anastasiyyya commented on Tests/src/test/java/tests/FlightDataTests.java
> +    @Test(description = "Checks that the input field works correctly")
исправила, всё работает

2021-09-27 07:50 UTC, merged